bpf: Replace inline asm with call to BPF helper function
[ upstream commit bc13b39af1c9d66e1591e66e5ebc880860e4a778 ]

Previously, in bpf_alignchecker.c we used inline asm to prevent
compiler from optimizing away unused variables. Unfortunately,
the support for inline asm in BPF code was added quite recently
to LLVM (2865ab6996 "bpf: add inline-asm support", Mon Sep 18 23:29:36
2017 +0000). Thus, with older versions of LLVM (e.g. 3.8.1),
the compilation of the program was failing with:

    error: couldn't allocate input reg for constraint 'r' at line
    2148004438

To prevent an older LLVM version from the optimization, we can pass
a reference to a var to any BPF helper function which accepts
a reference as an argument.

The workaround was suggested by Daniel Borkmann.

Signed-off-by: Martynas Pumputis <m@lambda.lt>
Signed-off-by: Joe Stringer <joe@cilium.io>